### ISSUE TITLE
'Toggle Capturing' hotkey disappears after switching tabs

### ISSUE THREAD

**Issue by cprogrammer1994** [keycastr/keycastr#105]
Toggle capturing just disappeared and recording is bound to the key `A` that makes the app not usable.

Version: [v0.9.5](https://github.com/keycastr/keycastr/releases/download/v0.9.5/KeyCastr.app.zip)

![image](https://user-images.githubusercontent.com/11232402/33476661-66d1d952-d68b-11e7-962e-bb4507507a91.png)

Where is the config file located?

**Comment by akitchen** [comment]
Thanks for reporting. Looks like there's a layout quirk in the latest macOS vs. that window's resizing behavior - I only see this after switching tabs, and I had to restart the app to get that field back.

The settings are stored in NSUserDefaults, so you're probably best off just restarting to get the text field back until this is fixed.

**Comment by cprogrammer1994** [comment]
- deleted the keycastr from the Applications folder.
- downloaded keycastr again.
- moved keycastr from the Downloads to the Applications.
- run keycastrs

Somehow the preferences remain.

![keycastr](https://user-images.githubusercontent.com/11232402/33593133-a5cd34b8-d996-11e7-82f7-91f243dab501.gif)

**Comment by akitchen** [comment]
It’s not clear from your screen recording - are you not able to change the ‘Toggle Capturing’ shortcut? I was able to change it on my machine without any issue.

**Comment by cprogrammer1994** [comment]
No, I am not.
It is `A` whatever I do.
Not sure how could I help resolving this :(
Does this happen to anyone else?

**Comment by akitchen** [comment]
I'm not sure how you got into this situation. Seems like there might be a bug in ShortcutRecorder (which provides the functionality here).

We'll look into updating it for the next release; meanwhile you may be able to use the `defaults` command in the terminal to fix the problem. For example, try running this in the terminal:

`defaults read net.stephendeken.KeyCastr`
and
`man defaults` for more info

**Comment by cprogrammer1994** [comment]
thank you!

**Comment by jachacha** [comment]
Hi there, 
I'v run into the same issue. Could you please describe more in dept how to use the defaults command in the terminal to fix the problem? 
Thank you.

**Comment by martin-martin** [comment]
The default key seems to set itself to this when it gets stuck:

```capturingHotKey = <00000000 00000000>;```

See my full output from running `defaults read net.stephendeken.KeyCastr`:

```
{
    "NSWindow Frame KCBezelWindow default.bezelWindow" = "10 10 1440 100 0 0 1440 877 ";
    SUEnableAutomaticChecks = 0;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2019-03-02 16:06:08 +0000";
    SUSendProfileInfo = 0;
    capturingHotKey = <00000000 00000000>;
    "default.commandKeysOnly" = 0;
    "default.fadeDelay" = "0.2243193069306927";
    "default.fadeDuration" = "0.08113010817825204";
    "default.fontSize" = "17.55167079207919";
    displayIcon = 1;
    selectedVisualizer = Default;
}
```

Maybe this can be helpful.

For me, restarting the app helped to be able to make it possible to change the toggle command again.

**Comment by martin-martin** [comment]
> Hi there,
> I'v run into the same issue. Could you please describe more in dept how to use the defaults command in the terminal to fix the problem?
> I am using the latest version: v0.9.6
> Thank you.

From `man defaults`:

```
     write domain key 'value'
                  Writes value as the value for key in domain.  value must be a property list, and must
                  be enclosed in single quotes.  For example:

                        defaults write com.companyname.appname "Default Color" '(255, 0, 0)'

                  sets the value for Default Color to an array containing the strings 255, 0, 0 (the red,
                  green, and blue components). Note that the key is enclosed in quotation marks because
                  it contains a space.
```

That means that typing:

```bash
defaults write net.stephendeken.KeyCastr capturingHotKey '<00001200 08000000>'
```

should change the shortcut to `cmd + shift + c`! Hope this helps @jachacha ! :)

**Comment by jachacha** [comment]
Hi Martin, 
thanks a lot, this really helped, now I have the shortcut at least set to something that wouldn't turn the recording on and off all the time. Is there a way how to disable the hotkey at all?
Cheers, 
Jarka

**Comment by luckman212** [comment]
This issue still persists on v0.9.8 + Catalina 10.15
The only way to get that field back is to quit the app and relaunch it

![image](https://user-images.githubusercontent.com/1992842/67683919-9dbf8480-f968-11e9-942b-9f07aa20350c.png)

**Comment by jqhan** [comment]
If you can't get the app to work on Mojave 10.14.6, you might want to try to use an old release version, v0.9.6 etc, if you want the app to be usable. Note that you might have to deal with the Accessibility API problem for this approach, which is discussed in [this issue](https://github.com/keycastr/keycastr/issues/146)

**Comment by akitchen** [comment]
The latest build works fine on Mojave, but Mojave seems a little quirky when it comes to accessibility API permissions. As much as I hate to say it, [rebooting seemed to help](https://github.com/keycastr/keycastr/issues/146#issuecomment-553784800).

**Comment by akitchen** [comment]
As to this issue, it's somewhere between our very old build of ShortcutRecorder and KeyCastr's antique `MainMenu.nib`. Ultimately we need to update ShortcutRecorder and possibly rebuild the nib if we want to be able to edit it in a modern Xcode.

**Comment by jsphkm** [comment]
I'm using KeyCastr 0.9.8 on macOS Catalina 10.15.4, and can confirm that this issue persists.  How do you remove the "A" shortcut from toggling?

**Comment by marq5** [comment]
> > Hi there,
> > I'v run into the same issue. Could you please describe more in dept how to use the defaults command in the terminal to fix the problem?
> > I am using the latest version: v0.9.6
> > Thank you.
> 
> From `man defaults`:
> 
> ```
> write domain key 'value'
>   Writes value as the value for key in domain.  value must be a property list, and must
>   be enclosed in single quotes.  For example:
> 
>         defaults write com.companyname.appname "Default Color" '(255, 0, 0)'
> 
>   sets the value for Default Color to an array containing the strings 255, 0, 0 (the red,
>   green, and blue components). Note that the key is enclosed in quotation marks because
>   it contains a space.
> ```
> 
> That means that typing:
> 
> ```shell
> defaults write net.stephendeken.KeyCastr capturingHotKey '<00001200 08000000>'
> ```
> 
> should change the shortcut to `cmd + shift + c`! Hope this helps @jachacha ! :)

Hi,

The terminal script changed the shortcut on my German localized user profile but didn't affect my English localized user profile. For my English user (on the same MBP Catalina) the shortcut is still "A" and can't be changed. Is that kind of strange or what?

**Comment by chrisman** [comment]
Currently working through this issue with v0.9.8 obtained with `brew cask install keycastr` on Catalina.

Looks as though the defaults are now at io.github.keycastr.

That is, you can see the defaults with `defaults read io.github.keycastr`

```
~> defaults read io.github.keycastr
{
    "NSWindow Frame KCBezelWindow default.bezelWindow" = "10 10 1440 100 0 0 1440 900 ";
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2020-07-17 19:29:48 +0000";
    SUSendProfileInfo = 0;
    capturingHotKey = {length = 8, bytes = 0x0000020032000000};
    "default.fontSize" = "64.63567450495049";
    displayIcon = 1;
    selectedVisualizer = Default;
}
```

Can anybody point me toward any documentation on the `capturingHotKey` format? I looked through `man defaults` and did a quick ddg but didn't see anything helpful.

**Comment by akitchen** [comment]
This is fixed on the main branch as a part of the MainMenu.nib modernizations in v0.9.10, coming soon™

**Comment by cabaalexander** [comment]
I want to change the a key to other like option/alt so when I'm writing it does not activate and deactivate :/

This issue is still happening:

![image](https://user-images.githubusercontent.com/12496574/125018005-3bc28800-e042-11eb-8cee-0c8faeb82b1f.png)

![image](https://user-images.githubusercontent.com/12496574/125018035-454bf000-e042-11eb-853d-0b33e2aaa61a.png)

**Comment by Arvidchen** [comment]
Hello, 

the issue still persists on Big Sur 11.6

I am running on a german keyboard. But i can´t change the CaptureKey. It isn´t displayed at all.

Besides the tool works great! Many thanks!

Merry Christmas
Arvid

**Comment by austinfinnql** [comment]
I am using version 0.9.16 on Sonoma 14.1 and I just came across the issue. Does anyone have any suggestions on how to change the stop/start value to some random collection of characters (so it never switches off)
